### PR TITLE
Add allocation hoist optimization

### PR DESCRIPTION
**Pull request by arshajii**

### CODE REVIEW

**Comment by marioroy** [comment]
The `alloc-hoist-opt` branch core-dumps running the [murphy.py](https://github.com/exaloop/codon/issues/478) demonstration.

```bash
# Codon 0.16.3
codon build -release murphy.py
time ./murphy
5.797

real  1m29.675s
user  4m44.102s
sys   0m35.530s


# Codon develop branch
codon build -release murphy.py
time ./murphy
5.797

real  0m49.610s
user  3m15.357s
sys   0m19.421s


# Codon alloc-hoist-opt branch
codon build -release murphy.py
time ./murphy
AssertionError: Assert failed (/tmp/murphy.py:104)

Raised from: play:0
/tmp/murphy.py:104:5
Aborted (core dumped)

real  0m0.411s
user  0m0.180s
sys   0m0.198s
```

Linue 104 is `assert len(scenarios) == 1`.

**Comment by arshajii** [comment]
Thanks @marioroy -- I've fixed this. Also it seems like the linked issue is resolved, as on my machine the timings are now 40s for Python and 27s for Codon (haven't done a detailed benchmark though).

**Comment by marioroy** [comment]
The initial [murphy.py](https://github.com/exaloop/codon/issues/478#issue-1889301076) demonstration and [memorization suggestion](https://github.com/exaloop/codon/issues/478#issuecomment-1715160673) complete without errors. Codon, using develop or alloc-hoist-opt branch, is nearly 2 times faster than Codon 0.16.3.

```text
                          murphy.py   murphy2.py
miniconda python 3.11.7     51.532s      8.262s
miniconda python 3.12.1     55.041s      8.739s
system python 3.12.1        57.168s      8.948s
codon 0.16.3              1m29.023s      8.226s
codon develop               49.779s      4.814s
codon alloc-hoist-opt       49.836s      4.755s
```

**Comment by marioroy** [comment]
```text
# Times taken above
codon 0.16.3              1m29.023s      8.226s
codon develop               49.779s      4.814s
codon alloc-hoist-opt       49.836s      4.755s
# hoist latest
codon alloc-hoist-opt       39.387s      4.092s
```

**Pull request merged**
