### PR TITLE
Constructing std::unique_ptr<Node> in place to improve performance for C++ binary trees benchmark

### PR DESCRIPTION
**Pull request by stephenberry**
Codon uses garbage collection, so I feel like this problem should permit using a memory pool, as would be common in this kind of problem. There are other ways to make the original code faster without a pool, but I think this makes the most sense.

### CODE REVIEW

**Comment by arshajii** [comment]
Actually this benchmark is also from pyperformance, even though it doesn't say so in the README. The point of this benchmark is to measure repeated dynamic memory allocation, so I don't think it makes sense to avoid it altogether in the C++ version.

We *could* use a memory pool with e.g. raw `new` that gets freed at the end. `std::unique_ptr` is generally more idiomatic, but maybe raw `new` is faster.

**Comment by stephenberry** [comment]
I think unique_ptr is fine if you want to test dynamic memory allocation. I'll change this pull request back to unique_ptr, but with some minor optimizations. The Node should be constructed in place.

**Comment by stephenberry** [comment]
I changed the code back to using unique_ptr, just more efficiently. The pool approach is technically a form of dynamic memory allocation, but I get it if you want to test new/delete performance in a fragmented context.

**Comment by arshajii** [comment]
Thanks! This looks good -- just a couple minor comments:

- Can we keep the anonymous namespace? This shouldn't affect performance and makes it easier to inspect any generated LLVM IR after inlining etc.
- Can we `clang-format` the file using the `.clang-format` in the root of the repo? Should be just `clang-format --style=file -i file.cpp`. For example right now there is some trailing whitespace.

Thanks again :)

**Comment by stephenberry** [comment]
I ran clang format on the code

**Pull request merged**
